### ISSUE TITLE
make load时 出现错误

### ISSUE THREAD

**Issue by bbblq** [anshengme/cash#1]
报错如下
docker-compose exec api sh -c "cd /src && make load"
ERROR: No container found for api_1
make: *** [load] Error 1

访问网站 先正常加载 然后只显示背景 提示502错误

**Comment by anshengme** [comment]
已修复，请尝试使用
```bash
# 启动所需要的服务
$ make up
# 查看日志已确保django启动
$ make logs  # 类似出现api_1_CONTAINER_ID | python3 manage.py runserver 0:9006
# 导入默认数据
$ make load
```
